version: '3'

services:
  
  db:
    image: mysql
    ports:
      - "3306:3306"
    networks:
      main:
        aliases:
          - db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=forum
      - MYSQL_USER=forumuser
      - MYSQL_PASSWORD=bbdbe444288550204c968fe7002a97a9
    volumes:
      - ./data:/docker-entrypoint-initdb.d

  app:
    build: .
    #command: python3 manage.py runserver 0.0.0.0:8000
    command: gunicorn forum.wsgi:application --bind 0.0.0.0:8000 --workers 3 --reload
    networks:
      main:
        aliases:
          - app
    volumes:
      - .:/code
    working_dir: /code/forum
    ports:
      - "8000:8000"
    depends_on:
      - db

  web:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./conf/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
    networks:
      main:
        aliases:
          - web
    depends_on:
      - app

networks:
  main: